plugins {
    alias(libs.plugins.android.library)
    id 'maven-publish'
    id 'signing'
}

android {
    namespace 'com.sam.samba.debug'
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        minSdk 28

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    // Publish only the release variant, with sources + javadoc jars.
    publishing {
        singleVariant("release") {
            withSourcesJar()
            withJavadocJar()
        }
    }

}

group = 'io.github.zhaiyong4118'
version = '1.0.1'

publishing {
    publications {
        release(MavenPublication) {
            groupId = 'io.github.zhaiyong4118'
            artifactId = 'samba-debug'
            version = '1.0.1'

            afterEvaluate {
                from components.release
            }

            pom {
                name = 'SambaDebug'
                description = 'Samba server debug tool library for Android'
                url = 'https://github.com/zhaiyong4118/SambaDebugToolAndroid'

                licenses {
                    license {
                        name = 'Apache License, Version 2.0'
                        url = 'http://www.apache.org/licenses/LICENSE-2.0'
                    }
                }
                developers {
                    developer {
                        id = 'zhaiyong4118'
                        name = 'zhaiyong'
                        email = 'zhaiyongDev@163.com'
                    }
                }
                scm {
                    connection = 'scm:git:git://github.com/zhaiyong4118/SambaDebugToolAndroid.git'
                    developerConnection = 'scm:git:ssh://github.com/zhaiyong4118/SambaDebugToolAndroid.git'
                    url = 'https://github.com/zhaiyong4118/SambaDebugToolAndroid'
                }
            }
        }
    }

    repositories {
        maven {
            // Maven Central (Central Portal OSSRH Staging API, for Gradle maven-publish)
            name = 'central'
            url = 'https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/'
            credentials {
                username = project.findProperty('ossrhUsername')
                password = project.findProperty('ossrhPassword')
            }
        }
    }
}

signing {
    sign publishing.publications.release
}

dependencies {
    implementation libs.androidx.appcompat
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.androidx.espresso.core
    androidTestImplementation libs.androidx.junit
}